table DimCustomer
	lineageTag: c7e42b4a-6113-430f-b3c0-a90287a5239b

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: c56053a6-7e04-4f5c-b3bc-b8e0ead1a723
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column MaritalStatus
		dataType: string
		lineageTag: a4760793-b02a-4536-9005-2ced07dc24b7
		summarizeBy: none
		sourceColumn: MaritalStatus

		annotation SummarizationSetBy = Automatic


	partition DimCustomer = m
		mode: import
		source =
			let
			Origen = Sql.Databases("localhost"),
			AdventureWorksDW2022 = Origen{[Name="AdventureWorksDW2022"]}[Data],
			dbo_DimCustomer = AdventureWorksDW2022{[Schema="dbo",Item="DimCustomer"]}[Data],
			#"Columnas quitadas" = Table.RemoveColumns(dbo_DimCustomer,{"AddressLine1", "AddressLine2", "BirthDate", "CommuteDistance", "CustomerAlternateKey", "DateFirstPurchase", "EmailAddress", "EnglishEducation", "EnglishOccupation", "FirstName", "FrenchEducation", "FrenchOccupation", "Gender", "GeographyKey", "HouseOwnerFlag", "LastName", "MiddleName", "NameStyle", "NumberCarsOwned", "NumberChildrenAtHome", "Phone", "SpanishEducation", "SpanishOccupation", "Suffix", "Title", "TotalChildren", "YearlyIncome"})
			in
			#"Columnas quitadas"