table InternetSales
	lineageTag: 0af0458f-9714-485f-a657-676541a01b76

	measure OrderQty = sum(InternetSales[OrderQuantity])
		formatString: 0
		lineageTag: 18149051-c55c-444a-9098-08780eae9cd7

	measure 'mi media' = sum(Product[ProductKey])
		formatString: 0
		lineageTag: 7a592c36-a85b-4dab-8e62-3ae3ff19dfcc

	measure Derivada = ([mi media] +[OrderQty]) * max(InternetSales[OrderDateKey])
		formatString: 0
		lineageTag: 1e68c339-2876-4787-a48e-a61c7c402c1f

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 7ead973e-d99b-4446-af3b-8616684aa4d7
		summarizeBy: none
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 293b4c42-3abd-49d6-a0b3-c44f2ad5401f
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column 'Fecha entrega'
		dataType: int64
		formatString: 0
		lineageTag: 6f4b13bb-30f4-4349-b2fe-7e36f9d7245c
		summarizeBy: none
		sourceColumn: Fecha entrega

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 334c57a7-56bd-43a0-a5c4-09adf2936c61
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 4e33089d-dd6f-4c56-8636-285035dd34b9
		summarizeBy: none
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column OrderQuantity
		dataType: int64
		formatString: 0
		lineageTag: 59013807-ff28-4900-a1d8-d87e7ae00baf
		summarizeBy: sum
		sourceColumn: OrderQuantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: decimal
		formatString: #,0.###############\ "€";-#,0.###############\ "€";#,0.###############\ "€"
		lineageTag: 4dab0018-12ed-40f3-93ef-0c9d16b3d516
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"es-ES"}

	column Columna = InternetSales[ProductKey]+100+InternetSales[CustomerKey]
		formatString: 0
		lineageTag: 507994b4-2641-48b5-bc1a-0e2b0aab219b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	hierarchy 'ProductKey Jerarquía'
		lineageTag: d3b92d8d-d71f-44b8-8a2e-ae93c46e8d83

		level ProductKey
			lineageTag: 2b2d5c16-efbf-415b-9062-0ceeb04afa52
			column: ProductKey

		level CustomerKey
			lineageTag: afb0cec0-1aaa-4657-bdee-b5f3fdbd5b1a
			column: CustomerKey

	partition InternetSales = m
		mode: import
		source =
				let
				Origen = Sql.Databases("A01P0717"),
				AdventureWorksDW2022 = Origen{[Name="AdventureWorksDW2022"]}[Data],
				dbo_FactInternetSales = AdventureWorksDW2022{[Schema="dbo",Item="FactInternetSales"]}[Data],
				#"Columnas quitadas" = Table.RemoveColumns(dbo_FactInternetSales,{"CarrierTrackingNumber", "CurrencyKey", "CustomerPONumber", "DiscountAmount", "DueDate", "ExtendedAmount", "Freight", "OrderDate", "ProductStandardCost", "PromotionKey", "RevisionNumber", "SalesOrderLineNumber", "SalesOrderNumber", "SalesTerritoryKey", "ShipDate", "TaxAmt", "TotalProductCost", "UnitPrice", "UnitPriceDiscountPct"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Columnas quitadas",{{"DueDateKey", "Fecha entrega"}})
				in
				#"Columnas con nombre cambiado"

	changedProperty = Name

